### ISSUE TITLE
Imgur uploading account is not correctly

### ISSUE THREAD

**Issue by vutamdung** [mrousavy/ImgurSniper#11]
Hi all,
I found some issues about uploading account of project and refresh token:

1. If we alway create new "ImgurClient" object with "ClientId" and "ClientSecret", we alway upload that image to application's account (see image: https://i.imgur.com/GuZ0wl4.png)
2. We alway call to "Login()" function on ImgurUploader class when rase upload action. This is not good solution for perfomence. I think we need check the "ExpiresIn" or "ExpiresAt" before refresh token.

Thanks!

**Comment by mrousavy** [comment]
Thanks for the issue! Take a look at my last 3-4 commits, I've "cached" the instance now. 👍
