### ISSUE TITLE
gif install ffmpegmanager error

### ISSUE THREAD

**Issue by yuzd** [mrousavy/ImgurSniper#16]
![image](https://user-images.githubusercontent.com/16083659/56947172-e4215b80-6b5e-11e9-96c1-899d473bf735.png)
![image](https://user-images.githubusercontent.com/16083659/56947225-0915ce80-6b5f-11e9-9684-5f42568e19e7.png)

**Comment by mrousavy** [comment]
Hi! can you attach the log or error file in your Documents Folder\ImgurSniper?

**Comment by yuzd** [comment]
![image](https://user-images.githubusercontent.com/16083659/56948170-e9cc7080-6b61-11e9-8660-318c309c92b2.png)

sorry i can not found any log files.

**Comment by yuzd** [comment]
is download ffmpeg err?

https://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-20170425-b4330a0-win64-static.zip

404

**Comment by mrousavy** [comment]
Yes, the release `20140425` was no longer available. I've updated the download string and published a new release. Tell me if it worked for you. 👍
