### ISSUE TITLE
API Library

### ISSUE THREAD

**Issue by TonyValenti** [mrousavy/ImgurSniper#19]
Hi @mrousavy -
We're interested in incorporating a "screenshot" capture feature into our app and we're willing to help fund the development of a library to do so.

1.  May we borrow your source code?
2.  Would you be willing to separate the Imgur portions of your code from the screen shotting portions to create a library we can consume?
3.  Would you be willing to incorporate basic editing features (like lightshot) into the UI?
4.  What would appropriate funding be to make the above happen?

**Comment by mrousavy** [comment]
Hi!
Thanks for reaching out to me, we can certainly find a solution. Please contact me on my email marcrousavy@hotmail.com.

**Comment by mrousavy** [comment]
I'm closing this issue since I got no response from you in 3 months. If you're still interested, send me an email, create another issue or hit me up with a carrier pigeon
