### ISSUE TITLE
Advice of GPL v3 violation

### ISSUE THREAD

**Issue by McoreD** [mrousavy/ImgurSniper#22]
Hi,

Whilst we all love OSS, I would like to raise a GPL violation. This project is currently under an MIT licence, and uses ShareX source code which is under GPL.

There is no evidence of crediting the use, and it is evident that the codebase is from ShareX.

The comparison provided below is from an older version of ShareX to demonstrate that the ShareX source code existed well before the ImgurSniper adoption of ShareX source code:

ImgurSniper: https://github.com/mrousavy/ImgurSniper/blob/master/ImgurSniper/Libraries/FFmpeg/ExternalCLIManager.cs
ShareX: https://github.com/ShareX/ShareX/blob/v11.7.0/ShareX.HelpersLib/CLI/ExternalCLIManager.cs

ImgurSniper: https://github.com/mrousavy/ImgurSniper/blob/master/ImgurSniper/Libraries/FFmpeg/FFmpegEnums.cs
ShareX: https://github.com/ShareX/ShareX/blob/v11.7.0/ShareX.ScreenCaptureLib/Enums.cs#L90

ImgurSniper: https://github.com/mrousavy/ImgurSniper/blob/master/ImgurSniper/Libraries/FFmpeg/FFmpegHelper.cs
ShareX: https://github.com/ShareX/ShareX/blob/v11.7.0/ShareX.ScreenCaptureLib/Screencast/FFmpegHelper.cs

ImgurSniper: https://github.com/mrousavy/ImgurSniper/blob/master/ImgurSniper/Libraries/FFmpeg/FFmpegOptions.cs
ShareX: https://github.com/ShareX/ShareX/blob/v11.7.0/ShareX.ScreenCaptureLib/Screencast/FFmpegOptions.cs

ImgurSniper: https://github.com/mrousavy/ImgurSniper/blob/master/ImgurSniper/Libraries/Helper/CursorData.cs
ShareX: https://github.com/ShareX/ShareX/blob/v11.7.0/ShareX.HelpersLib/CursorData.cs

ImgurSniper: https://github.com/mrousavy/ImgurSniper/blob/master/ImgurSniper/Libraries/Helper/Helpers.cs
ShareX: https://github.com/ShareX/ShareX/blob/v11.7.0/ShareX.HelpersLib/Helpers/Helpers.cs#L823

ImgurSniper: https://github.com/mrousavy/ImgurSniper/blob/master/ImgurSniper/Libraries/Native/NativeMethods.cs
ShareX: https://github.com/ShareX/ShareX/blob/v11.7.0/ShareX.HelpersLib/Native/NativeMethods.cs
https://github.com/ShareX/ShareX/blob/v11.7.0/ShareX.HelpersLib/Native/NativeMethods_Helpers.cs

ImgurSniper: https://github.com/mrousavy/ImgurSniper/blob/master/ImgurSniper/Libraries/ScreenCapture/ScreenRecorder.cs
ShareX: https://github.com/ShareX/ShareX/blob/v11.7.0/ShareX.ScreenCaptureLib/Screencast/ScreenRecorder.cs

ImgurSniper: https://github.com/mrousavy/ImgurSniper/blob/master/ImgurSniper/Libraries/ScreenCapture/ScreencastOptions.cs
ShareX: https://github.com/ShareX/ShareX/blob/v11.7.0/ShareX.ScreenCaptureLib/Screencast/ScreencastOptions.cs

ImgurSniper: https://github.com/mrousavy/ImgurSniper/blob/master/ImgurSniper/Libraries/ScreenCapture/Screenshot.cs
ShareX: https://github.com/ShareX/ShareX/blob/v11.7.0/ShareX.ScreenCaptureLib/Screenshot.cs#L117

We have also noticed that a portion of codes have been used in AnimatedGif which is another one of your repos:

AnimatedGif: https://github.com/mrousavy/AnimatedGif/tree/master/AnimatedGif
ShareX: https://github.com/ShareX/ShareX/tree/v11.7.0/ShareX.HelpersLib/GIF

AnimatedGif: https://github.com/mrousavy/AnimatedGif/blob/master/AnimatedGif/VideoEncoder.cs
ShareX: https://github.com/ShareX/ShareX/blob/v11.7.0/ShareX.HelpersLib/EncoderProgram.cs

GPL cannot be sublicensed, and if reused, then the project that uses it needs to be GPL too.
Please refer to:
https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)

Please provide credit where it is due, and review your licence by CoB 1 August 2020.

Thanks
Michael
ShareX Co-founder

**Comment by mrousavy** [comment]
You're right, not providing credit where it is due is a dick move. Updated LICENSE to GPL and added the GPL v3 license information at the files you mentioned.
